// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOo0AYNeaaVHUZtSNu5NNqJX0x3PxsVPw',
    appId: '1:275973356026:web:ab1a1bee0ffff9f73c8c43',
    messagingSenderId: '275973356026',
    projectId: 'skillswap-c7e8b',
    authDomain: 'skillswap-c7e8b.firebaseapp.com',
    storageBucket: 'skillswap-c7e8b.firebasestorage.app',
    measurementId: 'G-D2WRDG245Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9q4Y_lQmoUZvRdMjuKiTPHbjfWpzvg8',
    appId: '1:275973356026:android:35a2827feb8ef8df3c8c43',
    messagingSenderId: '275973356026',
    projectId: 'skillswap-c7e8b',
    storageBucket: 'skillswap-c7e8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSTA57ZbSSyeU1qF3sSsKuCAjqUhUOj8',
    appId: '1:275973356026:ios:b67e6ae071609df83c8c43',
    messagingSenderId: '275973356026',
    projectId: 'skillswap-c7e8b',
    storageBucket: 'skillswap-c7e8b.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSTA57ZbSSyeU1qF3sSsKuCAjqUhUOj8',
    appId: '1:275973356026:ios:b67e6ae071609df83c8c43',
    messagingSenderId: '275973356026',
    projectId: 'skillswap-c7e8b',
    storageBucket: 'skillswap-c7e8b.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOo0AYNeaaVHUZtSNu5NNqJX0x3PxsVPw',
    appId: '1:275973356026:web:e7caa136a9f8bfb63c8c43',
    messagingSenderId: '275973356026',
    projectId: 'skillswap-c7e8b',
    authDomain: 'skillswap-c7e8b.firebaseapp.com',
    storageBucket: 'skillswap-c7e8b.firebasestorage.app',
    measurementId: 'G-8LLB70Q1ND',
  );
}
